name: CI/CD deploy release

on:
  push:
    branches: ["deploy-release"]
  pull_request:
    branches: ["deploy-release"]

permissions:
  contents: write

jobs:
  ci_cd_deploy_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 20.x
        uses: actions/setup-node@v1
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install  

      - name: Run Unit Tests
        run: |
          npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI

      - name: Build Angular app
        run: npm run build --configuration production


      - name: List output folder
        run: ls -la dist/mycv/browser

      - name: Copy index.html, CSS, JS to docs
        run: |
          mkdir -p docs
          cp dist/mycv/browser/*.* docs/

      - name: List docs folder
        run: ls -la docs

      - name: Git commit and push docs
        env:
         CI_COMMIT_MESSAGE: deploy my cv to github pages
         CI_COMMIT_AUTHOR: Ricardo2099
         run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "rojasricardo104@gmail.com"
          git add docs
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}" || echo "No changes to commit"
          git push


