name: CI/CD Deploy Master

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install

      - name: Build Angular, output in dist/mycv
        run: |
          CI=false npm run build

      - name: Show build directory
        run: |
          ls -la dist/mycv/browser

      - name: Download and run httpd container
        run: |
          docker run -d --name serving_base httpd

      - name: Show running containers
        run: docker ps

      - name: Copy Angular build to container
        run: |
          docker cp dist/mycv/browser/. serving_base:/usr/local/apache2/htdocs

      - name: List contents inside container
        run: |
          docker exec serving_base ls -la /usr/local/apache2/htdocs

      - name: Build custom Docker image
        run: |
          docker commit --change "ENV MODEL_NAME mycv" serving_base ${{ secrets.DOCKER_USER }}/mycv:${{ github.sha }}

      - name: Show Docker images
        run: docker images

      - name: Docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USER }}/mycv:${{ github.sha }}
